name: Node.js CI

on:
  push:
    branches: [main]

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run a test command
        run: echo "The trigger is working!"

