name: Main CI

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  # Call the reusable workflow for Node 20
  build-node-20:
    uses: ./.github/workflows/reusable-build.yml
    with:
      node-version: '20'
      run-lint: true

  # Call the EXACT SAME template again, but for Node 18 and no linting!
  build-node-18:
    uses: ./.github/workflows/reusable-build.yml
    with:
      node-version: '18'
      run-lint: false